import 'package:flutter/material.dart';

/// Icons are stored by name, so the picker and the saved data stay readable.
/// Every name here must exist in [kIcons] or it falls back to a label.
const Map<String, List<String>> kIconCategories = {
  'Bathroom': ['shower', 'bathtub', 'soap', 'sanitizer', 'dry_cleaning', 'wc'],
  'Clothes': ['checkroom', 'local_laundry_service', 'iron', 'style', 'shopping_bag', 'diamond'],
  'Household': ['home', 'bed', 'chair', 'kitchen', 'cleaning_services', 'yard'],
  'School': ['school', 'book', 'edit_note', 'calculate', 'science', 'backpack'],
  'Office': ['work', 'mail', 'call', 'print', 'description', 'pie_chart'],
  'Transport': ['directions_car', 'directions_bus', 'train', 'flight', 'pedal_bike', 'directions_walk'],
  'Activities': ['fitness_center', 'sports_soccer', 'pool', 'hiking', 'self_improvement', 'sports_tennis'],
  'Food': ['restaurant', 'local_cafe', 'local_bar', 'bakery_dining', 'lunch_dining', 'egg_alt'],
  'Health': ['medical_services', 'medication', 'favorite', 'monitor_heart', 'vaccines', 'healing'],
  'Digital': ['smartphone', 'laptop_mac', 'wifi', 'cloud', 'headphones', 'videogame_asset'],
  'Nature': ['park', 'pets', 'sunny', 'water_drop', 'forest', 'eco'],
  'Symbols': ['label', 'star', 'flag', 'bolt', 'priority_high', 'done_all'],
};

const Map<String, IconData> kIcons = {
  'shower': Icons.shower,
  'bathtub': Icons.bathtub,
  'soap': Icons.soap,
  'sanitizer': Icons.sanitizer,
  'dry_cleaning': Icons.dry_cleaning,
  'wc': Icons.wc,
  'checkroom': Icons.checkroom,
  'local_laundry_service': Icons.local_laundry_service,
  'iron': Icons.iron,
  'style': Icons.style,
  'shopping_bag': Icons.shopping_bag,
  'diamond': Icons.diamond,
  'home': Icons.home,
  'bed': Icons.bed,
  'chair': Icons.chair,
  'kitchen': Icons.kitchen,
  'cleaning_services': Icons.cleaning_services,
  'yard': Icons.yard,
  'school': Icons.school,
  'book': Icons.book,
  'edit_note': Icons.edit_note,
  'calculate': Icons.calculate,
  'science': Icons.science,
  'backpack': Icons.backpack,
  'work': Icons.work,
  'mail': Icons.mail,
  'call': Icons.call,
  'print': Icons.print,
  'description': Icons.description,
  'pie_chart': Icons.pie_chart,
  'directions_car': Icons.directions_car,
  'directions_bus': Icons.directions_bus,
  'train': Icons.train,
  'flight': Icons.flight,
  'pedal_bike': Icons.pedal_bike,
  'directions_walk': Icons.directions_walk,
  'directions_run': Icons.directions_run,
  'fitness_center': Icons.fitness_center,
  'sports_soccer': Icons.sports_soccer,
  'pool': Icons.pool,
  'hiking': Icons.hiking,
  'self_improvement': Icons.self_improvement,
  'sports_tennis': Icons.sports_tennis,
  'restaurant': Icons.restaurant,
  'local_cafe': Icons.local_cafe,
  'local_bar': Icons.local_bar,
  'bakery_dining': Icons.bakery_dining,
  'lunch_dining': Icons.lunch_dining,
  'egg_alt': Icons.egg_alt,
  'medical_services': Icons.medical_services,
  'medication': Icons.medication,
  'favorite': Icons.favorite,
  'monitor_heart': Icons.monitor_heart,
  'vaccines': Icons.vaccines,
  'healing': Icons.healing,
  'smartphone': Icons.smartphone,
  'laptop_mac': Icons.laptop_mac,
  'wifi': Icons.wifi,
  'cloud': Icons.cloud,
  'headphones': Icons.headphones,
  'videogame_asset': Icons.videogame_asset,
  'park': Icons.park,
  'pets': Icons.pets,
  'sunny': Icons.sunny,
  'water_drop': Icons.water_drop,
  'forest': Icons.forest,
  'eco': Icons.eco,
  'label': Icons.label,
  'star': Icons.star,
  'flag': Icons.flag,
  'bolt': Icons.bolt,
  'priority_high': Icons.priority_high,
  'done_all': Icons.done_all,
  'groups': Icons.groups,
  'bedtime': Icons.bedtime,
  'inbox': Icons.inbox,
  'checklist': Icons.checklist,
  'local_fire_department': Icons.local_fire_department,
  'settings': Icons.settings,
  'view_timeline': Icons.view_timeline,
  'schedule': Icons.schedule,
};

IconData iconFor(String name) => kIcons[name] ?? Icons.label;
